// Code generated by hertz generator.

package ping

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	ping "github.com/fahmiauliarahman/golang-api-starter/biz/model/api/ping"
)

// Health .
// @router /health [GET]
func Health(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ping.HealthRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := &ping.HealthResponse{
		Message: "OK",
	}

	c.JSON(consts.StatusOK, resp)
}
