// Code generated by hertz generator.

package health

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	health "github.com/fahmiauliarahman/golang-api-starter/biz/model/api/health"
)

// Health .
// @router /health [GET]
func Health(ctx context.Context, c *app.RequestContext) {
	var err error
	var req health.HealthRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(health.HealthResponse)

	c.JSON(consts.StatusOK, resp)
}
